### ISSUE TITLE
Vuepress Next ( 2.0 ) Support

### ISSUE THREAD

**Issue by selected-pixel-jameson** [kawarimidoll/vuepress-plugin-tailwind#104]
Does this work with Vuepress 2.0?

**Comment by kawarimidoll** [comment]
Currently no...
I will update this for VuePress2 after it release as stable.

**Comment by selected-pixel-jameson** [comment]
It's pretty stable at this point. Releases are not introducing breaking changes that often. There is very little left on their roadmap outside of documentation and a dark theme.

**Comment by kawarimidoll** [comment]
Thank you, I will check that if I make time.

**Comment by Benbinbin** [comment]
@selected-pixel-jameson this [solution](https://github.com/vuepress/vuepress-next/discussions/116#discussioncomment-856167) maybe work.

**Comment by Benbinbin** [comment]
I use default theme and Vite as bundler, it works for me by applying [this](https://github.com/vuepress/vuepress-next/discussions/116#discussioncomment-858910) setting
