### ISSUE TITLE
Breaks my pages

### ISSUE THREAD

**Issue by mspoulsen** [kawarimidoll/vuepress-plugin-tailwind#30]
When I install the plugin the standard formatting of my pages is broken. 

Before:
![plugin-before](https://user-images.githubusercontent.com/10956790/92149827-d3ea5200-ee1e-11ea-94ce-27531889c1ab.png)

After:
![plugin-after](https://user-images.githubusercontent.com/10956790/92149839-d8af0600-ee1e-11ea-9993-ad188f629d11.png)

Any ideas?

**Comment by kawarimidoll** [comment]
Tailwind CSS resets styles to avoid to conflict with the other style settings.

If you use the default styles of vuepress, use options of this plugin:
``` js
// .vuepress/config.js
module.exports = {
  plugins: [
    [
      "@kawarimidoll/tailwind",
      {
        tailwindConfig: { 
          corePlugins: {
            preflight: false,
          }
        }
      }
    ],
  ]
};
```

or use configuration file:
``` js
// tailwind.config.js (in the same directory as package.json)
module.exports = {
  corePlugins: {
    preflight: false,
  }
};
```

For more information, refer this page: [Disabling Preflight - Tailwind CSS](https://tailwindcss.com/docs/preflight#disabling-preflight)

**Comment by mspoulsen** [comment]
If I do that tailwind is basically not working. Buttons are not flat and there are many other issues...?

**Comment by kawarimidoll** [comment]
I'm sorry, I can't reproduce your problem. It works in my development environment...
Do you use other style plugins or themes? There may be other reset css.
